// THIS FILE SHOULD BE AUTOMATICALLY GENERATED BY scripts/build_frame_sequence.py, EDIT ITS TEMPLATE THERE IF YOU WANT TO MODIFY THIS

export function load_slide_data() {
	var slide_data = {
		slides_dir: "build/png/",
		pause_image_indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 54, 99, 121, 166, 210, 211, 212, 213, 214, 215, 216, 217, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 314, 315, 316, 360, 361, 362, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449], // Animations will be used in between these image indices. We also assume the first and last slides are pause images
		fps: 30
	};
	return slide_data;
}